version: '2'
services:
    onlineshop-app:
        image: onlineshop
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://onlineshop-postgresql:5432/OnlineShop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    onlineshop-postgresql:
        extends:
            file: postgresql.yml
            service: onlineshop-postgresql
